// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: daemon/channel/pb/message_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message generated by proto-message-gen. DO NOT EDIT.
// source: tencent.p1298im.group_pro_proto.msgpush.C72444msgpush
//
// C72444msgpush is the message type for the C72444msgpush.
type MsgPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPush) Reset() {
	*x = MsgPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_message_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPush) ProtoMessage() {}

func (x *MsgPush) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_message_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPush.ProtoReflect.Descriptor instead.
func (*MsgPush) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_message_push_proto_rawDescGZIP(), []int{0}
}

// FocusInfo is the message type for the FocusInfo.
type MsgPush_FocusInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelIdList []uint64 `protobuf:"varint,1,rep,packed,name=channel_id_list,json=channelIdList,proto3" json:"channel_id_list,omitempty"` // uint64_channel_id_list
	GuildId       []uint64 `protobuf:"varint,2,rep,packed,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`                     // uint64_guild_id
}

func (x *MsgPush_FocusInfo) Reset() {
	*x = MsgPush_FocusInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_message_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPush_FocusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPush_FocusInfo) ProtoMessage() {}

func (x *MsgPush_FocusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_message_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPush_FocusInfo.ProtoReflect.Descriptor instead.
func (*MsgPush_FocusInfo) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_message_push_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MsgPush_FocusInfo) GetChannelIdList() []uint64 {
	if x != nil {
		return x.ChannelIdList
	}
	return nil
}

func (x *MsgPush_FocusInfo) GetGuildId() []uint64 {
	if x != nil {
		return x.GuildId
	}
	return nil
}

// MsgOnlinePush is the message type for the MsgOnlinePush.
type MsgPush_MsgOnlinePush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs         []*Common_Msg      `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`                                      // msgs
	GeneralFlag  uint32             `protobuf:"varint,2,opt,name=general_flag,json=generalFlag,proto3" json:"general_flag,omitempty"`    // general_flag
	NeedResp     uint32             `protobuf:"varint,3,opt,name=need_resp,json=needResp,proto3" json:"need_resp,omitempty"`             // need_resp
	ServerBuf    []byte             `protobuf:"bytes,4,opt,name=server_buf,json=serverBuf,proto3" json:"server_buf,omitempty"`           // server_buf
	CompressFlag uint32             `protobuf:"varint,5,opt,name=compress_flag,json=compressFlag,proto3" json:"compress_flag,omitempty"` // compress_flag
	CompressMsg  []byte             `protobuf:"bytes,6,opt,name=compress_msg,json=compressMsg,proto3" json:"compress_msg,omitempty"`     // compress_msg
	FocusInfo    *MsgPush_FocusInfo `protobuf:"bytes,7,opt,name=focus_info,json=focusInfo,proto3" json:"focus_info,omitempty"`           // focus_info
	HugeFlag     uint32             `protobuf:"varint,8,opt,name=huge_flag,json=hugeFlag,proto3" json:"huge_flag,omitempty"`             // huge_flag
}

func (x *MsgPush_MsgOnlinePush) Reset() {
	*x = MsgPush_MsgOnlinePush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_message_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPush_MsgOnlinePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPush_MsgOnlinePush) ProtoMessage() {}

func (x *MsgPush_MsgOnlinePush) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_message_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPush_MsgOnlinePush.ProtoReflect.Descriptor instead.
func (*MsgPush_MsgOnlinePush) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_message_push_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MsgPush_MsgOnlinePush) GetMsgs() []*Common_Msg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *MsgPush_MsgOnlinePush) GetGeneralFlag() uint32 {
	if x != nil {
		return x.GeneralFlag
	}
	return 0
}

func (x *MsgPush_MsgOnlinePush) GetNeedResp() uint32 {
	if x != nil {
		return x.NeedResp
	}
	return 0
}

func (x *MsgPush_MsgOnlinePush) GetServerBuf() []byte {
	if x != nil {
		return x.ServerBuf
	}
	return nil
}

func (x *MsgPush_MsgOnlinePush) GetCompressFlag() uint32 {
	if x != nil {
		return x.CompressFlag
	}
	return 0
}

func (x *MsgPush_MsgOnlinePush) GetCompressMsg() []byte {
	if x != nil {
		return x.CompressMsg
	}
	return nil
}

func (x *MsgPush_MsgOnlinePush) GetFocusInfo() *MsgPush_FocusInfo {
	if x != nil {
		return x.FocusInfo
	}
	return nil
}

func (x *MsgPush_MsgOnlinePush) GetHugeFlag() uint32 {
	if x != nil {
		return x.HugeFlag
	}
	return 0
}

// MsgPushResp is the message type for the MsgPushResp.
type MsgPush_MsgPushResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerBuf []byte `protobuf:"bytes,1,opt,name=server_buf,json=serverBuf,proto3" json:"server_buf,omitempty"` // server_buf
}

func (x *MsgPush_MsgPushResp) Reset() {
	*x = MsgPush_MsgPushResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_message_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPush_MsgPushResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPush_MsgPushResp) ProtoMessage() {}

func (x *MsgPush_MsgPushResp) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_message_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPush_MsgPushResp.ProtoReflect.Descriptor instead.
func (*MsgPush_MsgPushResp) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_message_push_proto_rawDescGZIP(), []int{0, 2}
}

func (x *MsgPush_MsgPushResp) GetServerBuf() []byte {
	if x != nil {
		return x.ServerBuf
	}
	return nil
}

// PressMsg is the message type for the PressMsg.
type MsgPush_PressMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs []*Common_Msg `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"` // msgs
}

func (x *MsgPush_PressMsg) Reset() {
	*x = MsgPush_PressMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_message_push_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPush_PressMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPush_PressMsg) ProtoMessage() {}

func (x *MsgPush_PressMsg) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_message_push_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPush_PressMsg.ProtoReflect.Descriptor instead.
func (*MsgPush_PressMsg) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_message_push_proto_rawDescGZIP(), []int{0, 3}
}

func (x *MsgPush_PressMsg) GetMsgs() []*Common_Msg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

// ServerBuf is the message type for the ServerBuf.
type MsgPush_ServerBuf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SvrIp   uint32 `protobuf:"varint,1,opt,name=svr_ip,json=svrIp,proto3" json:"svr_ip,omitempty"`       // svr_ip
	SvrPort uint32 `protobuf:"varint,2,opt,name=svr_port,json=svrPort,proto3" json:"svr_port,omitempty"` // svr_port
	EchoKey []byte `protobuf:"bytes,3,opt,name=echo_key,json=echoKey,proto3" json:"echo_key,omitempty"`  // echo_key
}

func (x *MsgPush_ServerBuf) Reset() {
	*x = MsgPush_ServerBuf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_message_push_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPush_ServerBuf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPush_ServerBuf) ProtoMessage() {}

func (x *MsgPush_ServerBuf) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_message_push_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPush_ServerBuf.ProtoReflect.Descriptor instead.
func (*MsgPush_ServerBuf) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_message_push_proto_rawDescGZIP(), []int{0, 4}
}

func (x *MsgPush_ServerBuf) GetSvrIp() uint32 {
	if x != nil {
		return x.SvrIp
	}
	return 0
}

func (x *MsgPush_ServerBuf) GetSvrPort() uint32 {
	if x != nil {
		return x.SvrPort
	}
	return 0
}

func (x *MsgPush_ServerBuf) GetEchoKey() []byte {
	if x != nil {
		return x.EchoKey
	}
	return nil
}

var File_daemon_channel_pb_message_push_proto protoreflect.FileDescriptor

var file_daemon_channel_pb_message_push_proto_rawDesc = []byte{
	0x0a, 0x24, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x75, 0x73, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8,
	0x04, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x1a, 0x4e, 0x0a, 0x09, 0x46, 0x6f,
	0x63, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x1a, 0xa7, 0x02, 0x0a, 0x0d, 0x4d,
	0x73, 0x67, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x04,
	0x6d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x62, 0x75, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x75, 0x66, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x46, 0x6c, 0x61,
	0x67, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x73,
	0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x4d, 0x73, 0x67, 0x12, 0x31, 0x0a, 0x0a, 0x66, 0x6f, 0x63, 0x75, 0x73, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x73, 0x67, 0x50, 0x75,
	0x73, 0x68, 0x2e, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x66, 0x6f,
	0x63, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x75, 0x67, 0x65, 0x5f,
	0x66, 0x6c, 0x61, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x68, 0x75, 0x67, 0x65,
	0x46, 0x6c, 0x61, 0x67, 0x1a, 0x2c, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x62, 0x75,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42,
	0x75, 0x66, 0x1a, 0x2b, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x1f,
	0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x1a,
	0x58, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x75, 0x66, 0x12, 0x15, 0x0a, 0x06,
	0x73, 0x76, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x76,
	0x72, 0x49, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x76, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x65, 0x63, 0x68, 0x6f, 0x4b, 0x65, 0x79, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x70, 0x35, 0x65, 0x2f, 0x70,
	0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_channel_pb_message_push_proto_rawDescOnce sync.Once
	file_daemon_channel_pb_message_push_proto_rawDescData = file_daemon_channel_pb_message_push_proto_rawDesc
)

func file_daemon_channel_pb_message_push_proto_rawDescGZIP() []byte {
	file_daemon_channel_pb_message_push_proto_rawDescOnce.Do(func() {
		file_daemon_channel_pb_message_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_channel_pb_message_push_proto_rawDescData)
	})
	return file_daemon_channel_pb_message_push_proto_rawDescData
}

var file_daemon_channel_pb_message_push_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_daemon_channel_pb_message_push_proto_goTypes = []interface{}{
	(*MsgPush)(nil),               // 0: MsgPush
	(*MsgPush_FocusInfo)(nil),     // 1: MsgPush.FocusInfo
	(*MsgPush_MsgOnlinePush)(nil), // 2: MsgPush.MsgOnlinePush
	(*MsgPush_MsgPushResp)(nil),   // 3: MsgPush.MsgPushResp
	(*MsgPush_PressMsg)(nil),      // 4: MsgPush.PressMsg
	(*MsgPush_ServerBuf)(nil),     // 5: MsgPush.ServerBuf
	(*Common_Msg)(nil),            // 6: Common.Msg
}
var file_daemon_channel_pb_message_push_proto_depIdxs = []int32{
	6, // 0: MsgPush.MsgOnlinePush.msgs:type_name -> Common.Msg
	1, // 1: MsgPush.MsgOnlinePush.focus_info:type_name -> MsgPush.FocusInfo
	6, // 2: MsgPush.PressMsg.msgs:type_name -> Common.Msg
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_daemon_channel_pb_message_push_proto_init() }
func file_daemon_channel_pb_message_push_proto_init() {
	if File_daemon_channel_pb_message_push_proto != nil {
		return
	}
	file_daemon_channel_pb_message_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_daemon_channel_pb_message_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_message_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPush_FocusInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_message_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPush_MsgOnlinePush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_message_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPush_MsgPushResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_message_push_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPush_PressMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_message_push_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPush_ServerBuf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_channel_pb_message_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daemon_channel_pb_message_push_proto_goTypes,
		DependencyIndexes: file_daemon_channel_pb_message_push_proto_depIdxs,
		MessageInfos:      file_daemon_channel_pb_message_push_proto_msgTypes,
	}.Build()
	File_daemon_channel_pb_message_push_proto = out.File
	file_daemon_channel_pb_message_push_proto_rawDesc = nil
	file_daemon_channel_pb_message_push_proto_goTypes = nil
	file_daemon_channel_pb_message_push_proto_depIdxs = nil
}
