// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: daemon/channel/pb/oidb_0xf62.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message generated by proto-message-gen. DO NOT EDIT.
// source: tencent.p1290im.group_pro_proto.oidb0xf62.Oidb0xf62
//
// Oidb0xf62 is the message type for the Oidb0xf62.
type Oidb0Xf62 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Oidb0Xf62) Reset() {
	*x = Oidb0Xf62{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb0Xf62) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb0Xf62) ProtoMessage() {}

func (x *Oidb0Xf62) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb0Xf62.ProtoReflect.Descriptor instead.
func (*Oidb0Xf62) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_oidb_0xf62_proto_rawDescGZIP(), []int{0}
}

// ReqBody is the message type for the ReqBody.
type Oidb0Xf62_ReqBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *Common_Msg `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` // f421631msg
}

func (x *Oidb0Xf62_ReqBody) Reset() {
	*x = Oidb0Xf62_ReqBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb0Xf62_ReqBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb0Xf62_ReqBody) ProtoMessage() {}

func (x *Oidb0Xf62_ReqBody) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb0Xf62_ReqBody.ProtoReflect.Descriptor instead.
func (*Oidb0Xf62_ReqBody) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_oidb_0xf62_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Oidb0Xf62_ReqBody) GetMsg() *Common_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

// RspBody is the message type for the RspBody.
type Oidb0Xf62_RspBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        uint32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`                                     // result
	Errmsg        []byte                  `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`                                      // errmsg
	SendTime      uint32                  `protobuf:"varint,3,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`                 // send_time
	Head          *Common_MsgHead         `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`                                          // head
	ErrType       uint32                  `protobuf:"varint,5,opt,name=err_type,json=errType,proto3" json:"err_type,omitempty"`                    // err_type
	TransSvrInfo  *Oidb0Xf62_TransSvrInfo `protobuf:"bytes,6,opt,name=trans_svr_info,json=transSvrInfo,proto3" json:"trans_svr_info,omitempty"`    // trans_svr_info
	FreqLimitInfo *Common_FreqLimitInfo   `protobuf:"bytes,7,opt,name=freq_limit_info,json=freqLimitInfo,proto3" json:"freq_limit_info,omitempty"` // freq_limit_info
}

func (x *Oidb0Xf62_RspBody) Reset() {
	*x = Oidb0Xf62_RspBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb0Xf62_RspBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb0Xf62_RspBody) ProtoMessage() {}

func (x *Oidb0Xf62_RspBody) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb0Xf62_RspBody.ProtoReflect.Descriptor instead.
func (*Oidb0Xf62_RspBody) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_oidb_0xf62_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Oidb0Xf62_RspBody) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Oidb0Xf62_RspBody) GetErrmsg() []byte {
	if x != nil {
		return x.Errmsg
	}
	return nil
}

func (x *Oidb0Xf62_RspBody) GetSendTime() uint32 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *Oidb0Xf62_RspBody) GetHead() *Common_MsgHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Oidb0Xf62_RspBody) GetErrType() uint32 {
	if x != nil {
		return x.ErrType
	}
	return 0
}

func (x *Oidb0Xf62_RspBody) GetTransSvrInfo() *Oidb0Xf62_TransSvrInfo {
	if x != nil {
		return x.TransSvrInfo
	}
	return nil
}

func (x *Oidb0Xf62_RspBody) GetFreqLimitInfo() *Common_FreqLimitInfo {
	if x != nil {
		return x.FreqLimitInfo
	}
	return nil
}

// TransSvrInfo is the message type for the TransSvrInfo.
type Oidb0Xf62_TransSvrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubType   uint32 `protobuf:"varint,1,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`      // sub_type
	RetCode   int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`      // ret_code
	ErrMsg    []byte `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`          // err_msg
	TransInfo []byte `protobuf:"bytes,4,opt,name=trans_info,json=transInfo,proto3" json:"trans_info,omitempty"` // trans_info
}

func (x *Oidb0Xf62_TransSvrInfo) Reset() {
	*x = Oidb0Xf62_TransSvrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb0Xf62_TransSvrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb0Xf62_TransSvrInfo) ProtoMessage() {}

func (x *Oidb0Xf62_TransSvrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb0Xf62_TransSvrInfo.ProtoReflect.Descriptor instead.
func (*Oidb0Xf62_TransSvrInfo) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_oidb_0xf62_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Oidb0Xf62_TransSvrInfo) GetSubType() uint32 {
	if x != nil {
		return x.SubType
	}
	return 0
}

func (x *Oidb0Xf62_TransSvrInfo) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *Oidb0Xf62_TransSvrInfo) GetErrMsg() []byte {
	if x != nil {
		return x.ErrMsg
	}
	return nil
}

func (x *Oidb0Xf62_TransSvrInfo) GetTransInfo() []byte {
	if x != nil {
		return x.TransInfo
	}
	return nil
}

var File_daemon_channel_pb_oidb_0xf62_proto protoreflect.FileDescriptor

var file_daemon_channel_pb_oidb_0xf62_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78, 0x66, 0x36, 0x32, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x03, 0x0a,
	0x09, 0x4f, 0x69, 0x64, 0x62, 0x30, 0x78, 0x66, 0x36, 0x32, 0x1a, 0x28, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x73, 0x67, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x1a, 0x94, 0x02, 0x0a, 0x07, 0x52, 0x73, 0x70, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65,
	0x61, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a,
	0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x73, 0x76, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x30, 0x78, 0x66, 0x36,
	0x32, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x53, 0x76, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x53, 0x76, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x0f,
	0x66, 0x72, 0x65, 0x71, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46,
	0x72, 0x65, 0x71, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x66, 0x72,
	0x65, 0x71, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x7c, 0x0a, 0x0c, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x53, 0x76, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x75, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73,
	0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x70, 0x35, 0x65, 0x2f, 0x70,
	0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_channel_pb_oidb_0xf62_proto_rawDescOnce sync.Once
	file_daemon_channel_pb_oidb_0xf62_proto_rawDescData = file_daemon_channel_pb_oidb_0xf62_proto_rawDesc
)

func file_daemon_channel_pb_oidb_0xf62_proto_rawDescGZIP() []byte {
	file_daemon_channel_pb_oidb_0xf62_proto_rawDescOnce.Do(func() {
		file_daemon_channel_pb_oidb_0xf62_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_channel_pb_oidb_0xf62_proto_rawDescData)
	})
	return file_daemon_channel_pb_oidb_0xf62_proto_rawDescData
}

var file_daemon_channel_pb_oidb_0xf62_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_daemon_channel_pb_oidb_0xf62_proto_goTypes = []interface{}{
	(*Oidb0Xf62)(nil),              // 0: Oidb0xf62
	(*Oidb0Xf62_ReqBody)(nil),      // 1: Oidb0xf62.ReqBody
	(*Oidb0Xf62_RspBody)(nil),      // 2: Oidb0xf62.RspBody
	(*Oidb0Xf62_TransSvrInfo)(nil), // 3: Oidb0xf62.TransSvrInfo
	(*Common_Msg)(nil),             // 4: Common.Msg
	(*Common_MsgHead)(nil),         // 5: Common.MsgHead
	(*Common_FreqLimitInfo)(nil),   // 6: Common.FreqLimitInfo
}
var file_daemon_channel_pb_oidb_0xf62_proto_depIdxs = []int32{
	4, // 0: Oidb0xf62.ReqBody.msg:type_name -> Common.Msg
	5, // 1: Oidb0xf62.RspBody.head:type_name -> Common.MsgHead
	3, // 2: Oidb0xf62.RspBody.trans_svr_info:type_name -> Oidb0xf62.TransSvrInfo
	6, // 3: Oidb0xf62.RspBody.freq_limit_info:type_name -> Common.FreqLimitInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_daemon_channel_pb_oidb_0xf62_proto_init() }
func file_daemon_channel_pb_oidb_0xf62_proto_init() {
	if File_daemon_channel_pb_oidb_0xf62_proto != nil {
		return
	}
	file_daemon_channel_pb_message_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb0Xf62); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb0Xf62_ReqBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb0Xf62_RspBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_oidb_0xf62_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb0Xf62_TransSvrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_channel_pb_oidb_0xf62_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daemon_channel_pb_oidb_0xf62_proto_goTypes,
		DependencyIndexes: file_daemon_channel_pb_oidb_0xf62_proto_depIdxs,
		MessageInfos:      file_daemon_channel_pb_oidb_0xf62_proto_msgTypes,
	}.Build()
	File_daemon_channel_pb_oidb_0xf62_proto = out.File
	file_daemon_channel_pb_oidb_0xf62_proto_rawDesc = nil
	file_daemon_channel_pb_oidb_0xf62_proto_goTypes = nil
	file_daemon_channel_pb_oidb_0xf62_proto_depIdxs = nil
}
