// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: daemon/channel/pb/service_common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message generated by proto-message-gen. DO NOT EDIT.
// source: tencent.p1318im.group_pro_proto.group_pro.comm.MsgSeq
//
// SvcCommon is the message type for the C73138common.
type SvcCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SvcCommon) Reset() {
	*x = SvcCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_service_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvcCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvcCommon) ProtoMessage() {}

func (x *SvcCommon) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_service_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvcCommon.ProtoReflect.Descriptor instead.
func (*SvcCommon) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_service_common_proto_rawDescGZIP(), []int{0}
}

// MsgSeq is the message type for the MsgSeq.
type SvcCommon_MsgSeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq  uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`   // uint64_seq
	Time uint64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"` // uint64_time
}

func (x *SvcCommon_MsgSeq) Reset() {
	*x = SvcCommon_MsgSeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_channel_pb_service_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvcCommon_MsgSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvcCommon_MsgSeq) ProtoMessage() {}

func (x *SvcCommon_MsgSeq) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_channel_pb_service_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvcCommon_MsgSeq.ProtoReflect.Descriptor instead.
func (*SvcCommon_MsgSeq) Descriptor() ([]byte, []int) {
	return file_daemon_channel_pb_service_common_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SvcCommon_MsgSeq) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SvcCommon_MsgSeq) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_daemon_channel_pb_service_common_proto protoreflect.FileDescriptor

var file_daemon_channel_pb_service_common_proto_rawDesc = []byte{
	0x0a, 0x26, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x09, 0x53, 0x76, 0x63, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x2e, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x70, 0x35, 0x65, 0x2f, 0x70, 0x65, 0x6e, 0x67, 0x75,
	0x69, 0x6e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_channel_pb_service_common_proto_rawDescOnce sync.Once
	file_daemon_channel_pb_service_common_proto_rawDescData = file_daemon_channel_pb_service_common_proto_rawDesc
)

func file_daemon_channel_pb_service_common_proto_rawDescGZIP() []byte {
	file_daemon_channel_pb_service_common_proto_rawDescOnce.Do(func() {
		file_daemon_channel_pb_service_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_channel_pb_service_common_proto_rawDescData)
	})
	return file_daemon_channel_pb_service_common_proto_rawDescData
}

var file_daemon_channel_pb_service_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_daemon_channel_pb_service_common_proto_goTypes = []interface{}{
	(*SvcCommon)(nil),        // 0: SvcCommon
	(*SvcCommon_MsgSeq)(nil), // 1: SvcCommon.MsgSeq
}
var file_daemon_channel_pb_service_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_daemon_channel_pb_service_common_proto_init() }
func file_daemon_channel_pb_service_common_proto_init() {
	if File_daemon_channel_pb_service_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daemon_channel_pb_service_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvcCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_channel_pb_service_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvcCommon_MsgSeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_channel_pb_service_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daemon_channel_pb_service_common_proto_goTypes,
		DependencyIndexes: file_daemon_channel_pb_service_common_proto_depIdxs,
		MessageInfos:      file_daemon_channel_pb_service_common_proto_msgTypes,
	}.Build()
	File_daemon_channel_pb_service_common_proto = out.File
	file_daemon_channel_pb_service_common_proto_rawDesc = nil
	file_daemon_channel_pb_service_common_proto_goTypes = nil
	file_daemon_channel_pb_service_common_proto_depIdxs = nil
}
