// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: daemon/service/pb/apollo_push_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message generated by proto-message-gen. DO NOT EDIT.
// source: tencent.p1318im.STPushMsgElem
//
// ApolloPushMessage is the message type for the apollo_push_msgInfo.
type ApolloPushMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApolloPushMessage) Reset() {
	*x = ApolloPushMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApolloPushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApolloPushMessage) ProtoMessage() {}

func (x *ApolloPushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApolloPushMessage.ProtoReflect.Descriptor instead.
func (*ApolloPushMessage) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_apollo_push_message_proto_rawDescGZIP(), []int{0}
}

// STPushMsgElem is the message type for the STPushMsgElem.
type ApolloPushMessage_STPushMsgElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      int32                                               `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`           // type
	ShowPlace uint32                                              `protobuf:"varint,2,opt,name=showPlace,proto3" json:"showPlace,omitempty"` // showPlace
	Priority  int32                                               `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`   // priority
	Pm1       *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1   `protobuf:"bytes,11,opt,name=pm1,proto3" json:"pm1,omitempty"`             // pm1
	Pm2       *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2   `protobuf:"bytes,12,opt,name=pm2,proto3" json:"pm2,omitempty"`             // pm2
	Pm3       []*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3 `protobuf:"bytes,13,rep,name=pm3,proto3" json:"pm3,omitempty"`             // pm3
	Pm4       []*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4 `protobuf:"bytes,14,rep,name=pm4,proto3" json:"pm4,omitempty"`             // pm4
}

func (x *ApolloPushMessage_STPushMsgElem) Reset() {
	*x = ApolloPushMessage_STPushMsgElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApolloPushMessage_STPushMsgElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApolloPushMessage_STPushMsgElem) ProtoMessage() {}

func (x *ApolloPushMessage_STPushMsgElem) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApolloPushMessage_STPushMsgElem.ProtoReflect.Descriptor instead.
func (*ApolloPushMessage_STPushMsgElem) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_apollo_push_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ApolloPushMessage_STPushMsgElem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem) GetShowPlace() uint32 {
	if x != nil {
		return x.ShowPlace
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem) GetPm1() *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1 {
	if x != nil {
		return x.Pm1
	}
	return nil
}

func (x *ApolloPushMessage_STPushMsgElem) GetPm2() *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2 {
	if x != nil {
		return x.Pm2
	}
	return nil
}

func (x *ApolloPushMessage_STPushMsgElem) GetPm3() []*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3 {
	if x != nil {
		return x.Pm3
	}
	return nil
}

func (x *ApolloPushMessage_STPushMsgElem) GetPm4() []*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4 {
	if x != nil {
		return x.Pm4
	}
	return nil
}

// STPushMsgElem0x1 is the message type for the STPushMsgElem0x1.
type ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionId   int32  `protobuf:"varint,1,opt,name=actionId,proto3" json:"actionId,omitempty"`     // actionId
	ActionType int32  `protobuf:"varint,2,opt,name=actionType,proto3" json:"actionType,omitempty"` // actionType
	SendUin    uint64 `protobuf:"varint,3,opt,name=sendUin,proto3" json:"sendUin,omitempty"`       // sendUin
	RcvUin     uint64 `protobuf:"varint,4,opt,name=rcvUin,proto3" json:"rcvUin,omitempty"`         // rcvUin
	AioType    int32  `protobuf:"varint,5,opt,name=aioType,proto3" json:"aioType,omitempty"`       // aioType
	SessionId  uint64 `protobuf:"varint,6,opt,name=sessionId,proto3" json:"sessionId,omitempty"`   // sessionId
	WordType   int32  `protobuf:"varint,7,opt,name=wordType,proto3" json:"wordType,omitempty"`     // wordType
	DiyWords   string `protobuf:"bytes,8,opt,name=diyWords,proto3" json:"diyWords,omitempty"`      // diyWords
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) Reset() {
	*x = ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) ProtoMessage() {}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1.ProtoReflect.Descriptor instead.
func (*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_apollo_push_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) GetActionId() int32 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) GetSendUin() uint64 {
	if x != nil {
		return x.SendUin
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) GetRcvUin() uint64 {
	if x != nil {
		return x.RcvUin
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) GetAioType() int32 {
	if x != nil {
		return x.AioType
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) GetWordType() int32 {
	if x != nil {
		return x.WordType
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1) GetDiyWords() string {
	if x != nil {
		return x.DiyWords
	}
	return ""
}

// STPushMsgElem0x2 is the message type for the STPushMsgElem0x2.
type ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUin    uint64 `protobuf:"varint,1,opt,name=toUin,proto3" json:"toUin,omitempty"`       // toUin
	ActionId int32  `protobuf:"varint,2,opt,name=actionId,proto3" json:"actionId,omitempty"` // actionId
	EndTs    uint64 `protobuf:"varint,3,opt,name=endTs,proto3" json:"endTs,omitempty"`       // endTs
	WordType int32  `protobuf:"varint,4,opt,name=wordType,proto3" json:"wordType,omitempty"` // wordType
	DiyWords string `protobuf:"bytes,5,opt,name=diyWords,proto3" json:"diyWords,omitempty"`  // diyWords
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) Reset() {
	*x = ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) ProtoMessage() {}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2.ProtoReflect.Descriptor instead.
func (*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_apollo_push_message_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) GetToUin() uint64 {
	if x != nil {
		return x.ToUin
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) GetActionId() int32 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) GetEndTs() uint64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) GetWordType() int32 {
	if x != nil {
		return x.WordType
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2) GetDiyWords() string {
	if x != nil {
		return x.DiyWords
	}
	return ""
}

// STPushMsgElem0x3 is the message type for the STPushMsgElem0x3.
type ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusType       uint32 `protobuf:"varint,1,opt,name=busType,proto3" json:"busType,omitempty"`             // busType
	BusId         uint32 `protobuf:"varint,2,opt,name=busId,proto3" json:"busId,omitempty"`                 // busId
	DotId         uint32 `protobuf:"varint,3,opt,name=dotId,proto3" json:"dotId,omitempty"`                 // dotId
	Priority      uint32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`           // priority
	BegTs         uint32 `protobuf:"varint,5,opt,name=begTs,proto3" json:"begTs,omitempty"`                 // begTs
	EndTs         uint32 `protobuf:"varint,6,opt,name=endTs,proto3" json:"endTs,omitempty"`                 // endTs
	Wording       string `protobuf:"bytes,7,opt,name=wording,proto3" json:"wording,omitempty"`              // wording
	Url           string `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`                      // url
	Theme         string `protobuf:"bytes,9,opt,name=theme,proto3" json:"theme,omitempty"`                  // theme
	ActId         string `protobuf:"bytes,10,opt,name=actId,proto3" json:"actId,omitempty"`                 // actId
	SpRegion      uint32 `protobuf:"varint,11,opt,name=spRegion,proto3" json:"spRegion,omitempty"`          // spRegion
	FolderIconUrl string `protobuf:"bytes,12,opt,name=folderIconUrl,proto3" json:"folderIconUrl,omitempty"` // folderIconUrl
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) Reset() {
	*x = ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) ProtoMessage() {}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3.ProtoReflect.Descriptor instead.
func (*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_apollo_push_message_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetBusType() uint32 {
	if x != nil {
		return x.BusType
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetBusId() uint32 {
	if x != nil {
		return x.BusId
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetDotId() uint32 {
	if x != nil {
		return x.DotId
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetBegTs() uint32 {
	if x != nil {
		return x.BegTs
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetEndTs() uint32 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetWording() string {
	if x != nil {
		return x.Wording
	}
	return ""
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetActId() string {
	if x != nil {
		return x.ActId
	}
	return ""
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetSpRegion() uint32 {
	if x != nil {
		return x.SpRegion
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3) GetFolderIconUrl() string {
	if x != nil {
		return x.FolderIconUrl
	}
	return ""
}

// STPushMsgElem0x4 is the message type for the STPushMsgElem0x4.
type ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid  uint32 `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`   // appid
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`      // name
	SrcVer uint32 `protobuf:"varint,3,opt,name=srcVer,proto3" json:"srcVer,omitempty"` // srcVer
	NewVer uint32 `protobuf:"varint,4,opt,name=newVer,proto3" json:"newVer,omitempty"` // newVer
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) Reset() {
	*x = ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) ProtoMessage() {}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_apollo_push_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4.ProtoReflect.Descriptor instead.
func (*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_apollo_push_message_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) GetAppid() uint32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) GetSrcVer() uint32 {
	if x != nil {
		return x.SrcVer
	}
	return 0
}

func (x *ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4) GetNewVer() uint32 {
	if x != nil {
		return x.NewVer
	}
	return 0
}

var File_daemon_service_pb_apollo_push_message_proto protoreflect.FileDescriptor

var file_daemon_service_pb_apollo_push_message_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x09,
	0x0a, 0x11, 0x41, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0xa4, 0x09, 0x0a, 0x0d, 0x53, 0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73,
	0x67, 0x45, 0x6c, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f,
	0x77, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x68,
	0x6f, 0x77, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x43, 0x0a, 0x03, 0x70, 0x6d, 0x31, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x31, 0x2e, 0x41, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c,
	0x65, 0x6d, 0x2e, 0x53, 0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65, 0x6d,
	0x30, 0x78, 0x31, 0x52, 0x03, 0x70, 0x6d, 0x31, 0x12, 0x43, 0x0a, 0x03, 0x70, 0x6d, 0x32, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x41, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x50, 0x75,
	0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x54, 0x50, 0x75, 0x73, 0x68,
	0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65, 0x6d, 0x2e, 0x53, 0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73,
	0x67, 0x45, 0x6c, 0x65, 0x6d, 0x30, 0x78, 0x32, 0x52, 0x03, 0x70, 0x6d, 0x32, 0x12, 0x43, 0x0a,
	0x03, 0x70, 0x6d, 0x33, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x41, 0x70, 0x6f,
	0x6c, 0x6c, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53,
	0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65, 0x6d, 0x2e, 0x53, 0x54, 0x50,
	0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65, 0x6d, 0x30, 0x78, 0x33, 0x52, 0x03, 0x70,
	0x6d, 0x33, 0x12, 0x43, 0x0a, 0x03, 0x70, 0x6d, 0x34, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x41, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65,
	0x6d, 0x2e, 0x53, 0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65, 0x6d, 0x30,
	0x78, 0x34, 0x52, 0x03, 0x70, 0x6d, 0x34, 0x1a, 0xf0, 0x01, 0x0a, 0x10, 0x53, 0x54, 0x50, 0x75,
	0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65, 0x6d, 0x30, 0x78, 0x31, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64,
	0x55, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x55,
	0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x63, 0x76, 0x55, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x63, 0x76, 0x55, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x69,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x69, 0x6f,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x69, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x69, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x92, 0x01, 0x0a, 0x10, 0x53,
	0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65, 0x6d, 0x30, 0x78, 0x32, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x74, 0x6f, 0x55, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x54, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x65, 0x6e, 0x64, 0x54, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x1a,
	0xba, 0x02, 0x0a, 0x10, 0x53, 0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65,
	0x6d, 0x30, 0x78, 0x33, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x75, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62,
	0x75, 0x73, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x64, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x54, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x65, 0x67, 0x54, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6e, 0x64, 0x54, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x6e, 0x64,
	0x54, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x49, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x70,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x70,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x49, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x1a, 0x6c, 0x0a, 0x10,
	0x53, 0x54, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x45, 0x6c, 0x65, 0x6d, 0x30, 0x78, 0x34,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x72,
	0x63, 0x56, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x72, 0x63, 0x56,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x56, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x56, 0x65, 0x72, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x70, 0x35, 0x65, 0x2f,
	0x70, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_daemon_service_pb_apollo_push_message_proto_rawDescOnce sync.Once
	file_daemon_service_pb_apollo_push_message_proto_rawDescData = file_daemon_service_pb_apollo_push_message_proto_rawDesc
)

func file_daemon_service_pb_apollo_push_message_proto_rawDescGZIP() []byte {
	file_daemon_service_pb_apollo_push_message_proto_rawDescOnce.Do(func() {
		file_daemon_service_pb_apollo_push_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_service_pb_apollo_push_message_proto_rawDescData)
	})
	return file_daemon_service_pb_apollo_push_message_proto_rawDescData
}

var file_daemon_service_pb_apollo_push_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_daemon_service_pb_apollo_push_message_proto_goTypes = []interface{}{
	(*ApolloPushMessage)(nil),                                // 0: ApolloPushMessage
	(*ApolloPushMessage_STPushMsgElem)(nil),                  // 1: ApolloPushMessage.STPushMsgElem
	(*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1)(nil), // 2: ApolloPushMessage.STPushMsgElem.STPushMsgElem0x1
	(*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2)(nil), // 3: ApolloPushMessage.STPushMsgElem.STPushMsgElem0x2
	(*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3)(nil), // 4: ApolloPushMessage.STPushMsgElem.STPushMsgElem0x3
	(*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4)(nil), // 5: ApolloPushMessage.STPushMsgElem.STPushMsgElem0x4
}
var file_daemon_service_pb_apollo_push_message_proto_depIdxs = []int32{
	2, // 0: ApolloPushMessage.STPushMsgElem.pm1:type_name -> ApolloPushMessage.STPushMsgElem.STPushMsgElem0x1
	3, // 1: ApolloPushMessage.STPushMsgElem.pm2:type_name -> ApolloPushMessage.STPushMsgElem.STPushMsgElem0x2
	4, // 2: ApolloPushMessage.STPushMsgElem.pm3:type_name -> ApolloPushMessage.STPushMsgElem.STPushMsgElem0x3
	5, // 3: ApolloPushMessage.STPushMsgElem.pm4:type_name -> ApolloPushMessage.STPushMsgElem.STPushMsgElem0x4
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_daemon_service_pb_apollo_push_message_proto_init() }
func file_daemon_service_pb_apollo_push_message_proto_init() {
	if File_daemon_service_pb_apollo_push_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daemon_service_pb_apollo_push_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApolloPushMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_apollo_push_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApolloPushMessage_STPushMsgElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_apollo_push_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_apollo_push_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_apollo_push_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_apollo_push_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApolloPushMessage_STPushMsgElem_STPushMsgElem0X4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_service_pb_apollo_push_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daemon_service_pb_apollo_push_message_proto_goTypes,
		DependencyIndexes: file_daemon_service_pb_apollo_push_message_proto_depIdxs,
		MessageInfos:      file_daemon_service_pb_apollo_push_message_proto_msgTypes,
	}.Build()
	File_daemon_service_pb_apollo_push_message_proto = out.File
	file_daemon_service_pb_apollo_push_message_proto_rawDesc = nil
	file_daemon_service_pb_apollo_push_message_proto_goTypes = nil
	file_daemon_service_pb_apollo_push_message_proto_depIdxs = nil
}
