// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: daemon/service/pb/oidb_0x769.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message generated by proto-message-gen. DO NOT EDIT.
// source: tencent.p1298im.oidb.cmd0x769.Oidb_0x769
//
// Oidb_0x769 is the message type for the Oidb_0x769.
type Oidb_0X769 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Oidb_0X769) Reset() {
	*x = Oidb_0X769{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769) ProtoMessage() {}

func (x *Oidb_0X769) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769.ProtoReflect.Descriptor instead.
func (*Oidb_0X769) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0}
}

// CPU is the message type for the CPU.
type Oidb_0X769_CPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model     string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`          // model
	Cores     uint32 `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`         // cores
	Frequency uint32 `protobuf:"varint,3,opt,name=frequency,proto3" json:"frequency,omitempty"` // frequency
}

func (x *Oidb_0X769_CPU) Reset() {
	*x = Oidb_0X769_CPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_CPU) ProtoMessage() {}

func (x *Oidb_0X769_CPU) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_CPU.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_CPU) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Oidb_0X769_CPU) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Oidb_0X769_CPU) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *Oidb_0X769_CPU) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

// Camera is the message type for the Camera.
type Oidb_0X769_Camera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primary   uint64 `protobuf:"varint,1,opt,name=primary,proto3" json:"primary,omitempty"`     // primary
	Secondary uint64 `protobuf:"varint,2,opt,name=secondary,proto3" json:"secondary,omitempty"` // secondary
	Flash     bool   `protobuf:"varint,3,opt,name=flash,proto3" json:"flash,omitempty"`         // flash
}

func (x *Oidb_0X769_Camera) Reset() {
	*x = Oidb_0X769_Camera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_Camera) ProtoMessage() {}

func (x *Oidb_0X769_Camera) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_Camera.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_Camera) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Oidb_0X769_Camera) GetPrimary() uint64 {
	if x != nil {
		return x.Primary
	}
	return 0
}

func (x *Oidb_0X769_Camera) GetSecondary() uint64 {
	if x != nil {
		return x.Secondary
	}
	return 0
}

func (x *Oidb_0X769_Camera) GetFlash() bool {
	if x != nil {
		return x.Flash
	}
	return false
}

// Config is the message type for the Config.
type Oidb_0X769_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type           uint32                `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`                                            // uint32_type
	Version        uint32                `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                      // uint32_version
	ContentList    []string              `protobuf:"bytes,3,rep,name=content_list,json=contentList,proto3" json:"content_list,omitempty"`            // rpt_content_list
	DebugMsg       string                `protobuf:"bytes,4,opt,name=debug_msg,json=debugMsg,proto3" json:"debug_msg,omitempty"`                     // debug_msg
	MsgContentList []*Oidb_0X769_Content `protobuf:"bytes,5,rep,name=msg_content_list,json=msgContentList,proto3" json:"msg_content_list,omitempty"` // rpt_msg_content_list
}

func (x *Oidb_0X769_Config) Reset() {
	*x = Oidb_0X769_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_Config) ProtoMessage() {}

func (x *Oidb_0X769_Config) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_Config.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_Config) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Oidb_0X769_Config) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Oidb_0X769_Config) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Oidb_0X769_Config) GetContentList() []string {
	if x != nil {
		return x.ContentList
	}
	return nil
}

func (x *Oidb_0X769_Config) GetDebugMsg() string {
	if x != nil {
		return x.DebugMsg
	}
	return ""
}

func (x *Oidb_0X769_Config) GetMsgContentList() []*Oidb_0X769_Content {
	if x != nil {
		return x.MsgContentList
	}
	return nil
}

// ConfigSeq is the message type for the ConfigSeq.
type Oidb_0X769_ConfigSeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`       // type
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // version
}

func (x *Oidb_0X769_ConfigSeq) Reset() {
	*x = Oidb_0X769_ConfigSeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_ConfigSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_ConfigSeq) ProtoMessage() {}

func (x *Oidb_0X769_ConfigSeq) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_ConfigSeq.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_ConfigSeq) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Oidb_0X769_ConfigSeq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Oidb_0X769_ConfigSeq) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Content is the message type for the Content.
type Oidb_0X769_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // task_id
	Compress uint32 `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`           // compress
	Content  []byte `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`             // content
}

func (x *Oidb_0X769_Content) Reset() {
	*x = Oidb_0X769_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_Content) ProtoMessage() {}

func (x *Oidb_0X769_Content) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_Content.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_Content) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Oidb_0X769_Content) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Oidb_0X769_Content) GetCompress() uint32 {
	if x != nil {
		return x.Compress
	}
	return 0
}

func (x *Oidb_0X769_Content) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// DeviceInfo is the message type for the DeviceInfo.
type Oidb_0X769_DeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand   string              `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`     // brand
	Model   string              `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`     // model
	Cpu     *Oidb_0X769_CPU     `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`         // cpu
	Memory  *Oidb_0X769_Memory  `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`   // memory
	Storage *Oidb_0X769_Storage `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"` // storage
	Screen  *Oidb_0X769_Screen  `protobuf:"bytes,7,opt,name=screen,proto3" json:"screen,omitempty"`   // screen
}

func (x *Oidb_0X769_DeviceInfo) Reset() {
	*x = Oidb_0X769_DeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_DeviceInfo) ProtoMessage() {}

func (x *Oidb_0X769_DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_DeviceInfo.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_DeviceInfo) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Oidb_0X769_DeviceInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Oidb_0X769_DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Oidb_0X769_DeviceInfo) GetCpu() *Oidb_0X769_CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Oidb_0X769_DeviceInfo) GetMemory() *Oidb_0X769_Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Oidb_0X769_DeviceInfo) GetStorage() *Oidb_0X769_Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Oidb_0X769_DeviceInfo) GetScreen() *Oidb_0X769_Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

// Memory is the message type for the Memory.
type Oidb_0X769_Memory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`     // total
	Process uint64 `protobuf:"varint,2,opt,name=process,proto3" json:"process,omitempty"` // process
}

func (x *Oidb_0X769_Memory) Reset() {
	*x = Oidb_0X769_Memory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_Memory) ProtoMessage() {}

func (x *Oidb_0X769_Memory) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_Memory.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_Memory) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Oidb_0X769_Memory) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Oidb_0X769_Memory) GetProcess() uint64 {
	if x != nil {
		return x.Process
	}
	return 0
}

// C72478OS is the message type for the C72478OS.
type Oidb_0X769_C72478OS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`      // type
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // version
	Sdk     string `protobuf:"bytes,3,opt,name=sdk,proto3" json:"sdk,omitempty"`         // sdk
	Kernel  string `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`   // kernel
	Rom     string `protobuf:"bytes,5,opt,name=rom,proto3" json:"rom,omitempty"`         // rom
}

func (x *Oidb_0X769_C72478OS) Reset() {
	*x = Oidb_0X769_C72478OS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_C72478OS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_C72478OS) ProtoMessage() {}

func (x *Oidb_0X769_C72478OS) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_C72478OS.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_C72478OS) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Oidb_0X769_C72478OS) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Oidb_0X769_C72478OS) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Oidb_0X769_C72478OS) GetSdk() string {
	if x != nil {
		return x.Sdk
	}
	return ""
}

func (x *Oidb_0X769_C72478OS) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *Oidb_0X769_C72478OS) GetRom() string {
	if x != nil {
		return x.Rom
	}
	return ""
}

// QueryUinPackageUsageReq is the message type for the QueryUinPackageUsageReq.
type Oidb_0X769_QueryUinPackageUsageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`                                    // type
	UinFileSize uint64 `protobuf:"varint,2,opt,name=uin_file_size,json=uinFileSize,proto3" json:"uin_file_size,omitempty"` // uin_file_size
}

func (x *Oidb_0X769_QueryUinPackageUsageReq) Reset() {
	*x = Oidb_0X769_QueryUinPackageUsageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_QueryUinPackageUsageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_QueryUinPackageUsageReq) ProtoMessage() {}

func (x *Oidb_0X769_QueryUinPackageUsageReq) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_QueryUinPackageUsageReq.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_QueryUinPackageUsageReq) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Oidb_0X769_QueryUinPackageUsageReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Oidb_0X769_QueryUinPackageUsageReq) GetUinFileSize() uint64 {
	if x != nil {
		return x.UinFileSize
	}
	return 0
}

// QueryUinPackageUsageRsp is the message type for the QueryUinPackageUsageRsp.
type Oidb_0X769_QueryUinPackageUsageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status             uint32                           `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                                                       // status
	LeftUinNum         uint64                           `protobuf:"varint,2,opt,name=left_uin_num,json=leftUinNum,proto3" json:"left_uin_num,omitempty"`                           // left_uin_num
	MaxUinNum          uint64                           `protobuf:"varint,3,opt,name=max_uin_num,json=maxUinNum,proto3" json:"max_uin_num,omitempty"`                              // max_uin_num
	Proportion         uint32                           `protobuf:"varint,4,opt,name=proportion,proto3" json:"proportion,omitempty"`                                               // proportion
	UinPackageUsedList []*Oidb_0X769_UinPackageUsedInfo `protobuf:"bytes,10,rep,name=uin_package_used_list,json=uinPackageUsedList,proto3" json:"uin_package_used_list,omitempty"` // uin_package_used_list
}

func (x *Oidb_0X769_QueryUinPackageUsageRsp) Reset() {
	*x = Oidb_0X769_QueryUinPackageUsageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_QueryUinPackageUsageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_QueryUinPackageUsageRsp) ProtoMessage() {}

func (x *Oidb_0X769_QueryUinPackageUsageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_QueryUinPackageUsageRsp.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_QueryUinPackageUsageRsp) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Oidb_0X769_QueryUinPackageUsageRsp) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Oidb_0X769_QueryUinPackageUsageRsp) GetLeftUinNum() uint64 {
	if x != nil {
		return x.LeftUinNum
	}
	return 0
}

func (x *Oidb_0X769_QueryUinPackageUsageRsp) GetMaxUinNum() uint64 {
	if x != nil {
		return x.MaxUinNum
	}
	return 0
}

func (x *Oidb_0X769_QueryUinPackageUsageRsp) GetProportion() uint32 {
	if x != nil {
		return x.Proportion
	}
	return 0
}

func (x *Oidb_0X769_QueryUinPackageUsageRsp) GetUinPackageUsedList() []*Oidb_0X769_UinPackageUsedInfo {
	if x != nil {
		return x.UinPackageUsedList
	}
	return nil
}

// ReqBody is the message type for the ReqBody.
type Oidb_0X769_ReqBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigList              []*Oidb_0X769_ConfigSeq             `protobuf:"bytes,1,rep,name=config_list,json=configList,proto3" json:"config_list,omitempty"`                                                // rpt_config_list
	MsgDeviceInfo           *Oidb_0X769_DeviceInfo              `protobuf:"bytes,2,opt,name=msg_device_info,json=msgDeviceInfo,proto3" json:"msg_device_info,omitempty"`                                     // msg_device_info
	Info                    string                              `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`                                                                              // str_info
	Province                string                              `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`                                                                      // province
	City                    string                              `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`                                                                              // city
	ReqDebugMsg             int32                               `protobuf:"varint,6,opt,name=req_debug_msg,json=reqDebugMsg,proto3" json:"req_debug_msg,omitempty"`                                          // req_debug_msg
	QueryUinPackageUsageReq *Oidb_0X769_QueryUinPackageUsageReq `protobuf:"bytes,101,opt,name=query_uin_package_usage_req,json=queryUinPackageUsageReq,proto3" json:"query_uin_package_usage_req,omitempty"` // query_uin_package_usage_req
}

func (x *Oidb_0X769_ReqBody) Reset() {
	*x = Oidb_0X769_ReqBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_ReqBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_ReqBody) ProtoMessage() {}

func (x *Oidb_0X769_ReqBody) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_ReqBody.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_ReqBody) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Oidb_0X769_ReqBody) GetConfigList() []*Oidb_0X769_ConfigSeq {
	if x != nil {
		return x.ConfigList
	}
	return nil
}

func (x *Oidb_0X769_ReqBody) GetMsgDeviceInfo() *Oidb_0X769_DeviceInfo {
	if x != nil {
		return x.MsgDeviceInfo
	}
	return nil
}

func (x *Oidb_0X769_ReqBody) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Oidb_0X769_ReqBody) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Oidb_0X769_ReqBody) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Oidb_0X769_ReqBody) GetReqDebugMsg() int32 {
	if x != nil {
		return x.ReqDebugMsg
	}
	return 0
}

func (x *Oidb_0X769_ReqBody) GetQueryUinPackageUsageReq() *Oidb_0X769_QueryUinPackageUsageReq {
	if x != nil {
		return x.QueryUinPackageUsageReq
	}
	return nil
}

// RspBody is the message type for the RspBody.
type Oidb_0X769_RspBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result                  uint32                              `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`                                                                         // uint32_result
	ConfigList              []*Oidb_0X769_Config                `protobuf:"bytes,2,rep,name=config_list,json=configList,proto3" json:"config_list,omitempty"`                                                // rpt_config_list
	QueryUinPackageUsageRsp *Oidb_0X769_QueryUinPackageUsageRsp `protobuf:"bytes,101,opt,name=query_uin_package_usage_rsp,json=queryUinPackageUsageRsp,proto3" json:"query_uin_package_usage_rsp,omitempty"` // query_uin_package_usage_rsp
}

func (x *Oidb_0X769_RspBody) Reset() {
	*x = Oidb_0X769_RspBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_RspBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_RspBody) ProtoMessage() {}

func (x *Oidb_0X769_RspBody) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_RspBody.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_RspBody) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Oidb_0X769_RspBody) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Oidb_0X769_RspBody) GetConfigList() []*Oidb_0X769_Config {
	if x != nil {
		return x.ConfigList
	}
	return nil
}

func (x *Oidb_0X769_RspBody) GetQueryUinPackageUsageRsp() *Oidb_0X769_QueryUinPackageUsageRsp {
	if x != nil {
		return x.QueryUinPackageUsageRsp
	}
	return nil
}

// Screen is the message type for the Screen.
type Oidb_0X769_Screen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model      string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                              // model
	Width      uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`                             // width
	Height     uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                           // height
	Dpi        uint32 `protobuf:"varint,4,opt,name=dpi,proto3" json:"dpi,omitempty"`                                 // dpi
	MultiTouch bool   `protobuf:"varint,5,opt,name=multi_touch,json=multiTouch,proto3" json:"multi_touch,omitempty"` // multi_touch
}

func (x *Oidb_0X769_Screen) Reset() {
	*x = Oidb_0X769_Screen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_Screen) ProtoMessage() {}

func (x *Oidb_0X769_Screen) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_Screen.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_Screen) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 12}
}

func (x *Oidb_0X769_Screen) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Oidb_0X769_Screen) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Oidb_0X769_Screen) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Oidb_0X769_Screen) GetDpi() uint32 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

func (x *Oidb_0X769_Screen) GetMultiTouch() bool {
	if x != nil {
		return x.MultiTouch
	}
	return false
}

// Storage is the message type for the Storage.
type Oidb_0X769_Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Builtin  uint64 `protobuf:"varint,1,opt,name=builtin,proto3" json:"builtin,omitempty"`   // builtin
	External uint64 `protobuf:"varint,2,opt,name=external,proto3" json:"external,omitempty"` // external
}

func (x *Oidb_0X769_Storage) Reset() {
	*x = Oidb_0X769_Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_Storage) ProtoMessage() {}

func (x *Oidb_0X769_Storage) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_Storage.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_Storage) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 13}
}

func (x *Oidb_0X769_Storage) GetBuiltin() uint64 {
	if x != nil {
		return x.Builtin
	}
	return 0
}

func (x *Oidb_0X769_Storage) GetExternal() uint64 {
	if x != nil {
		return x.External
	}
	return 0
}

// UinPackageUsedInfo is the message type for the UinPackageUsedInfo.
type Oidb_0X769_UinPackageUsedInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId uint32 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"` // rule_id
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`                // author
	Url    string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                      // url
	UinNum uint64 `protobuf:"varint,4,opt,name=uin_num,json=uinNum,proto3" json:"uin_num,omitempty"` // uin_num
}

func (x *Oidb_0X769_UinPackageUsedInfo) Reset() {
	*x = Oidb_0X769_UinPackageUsedInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oidb_0X769_UinPackageUsedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oidb_0X769_UinPackageUsedInfo) ProtoMessage() {}

func (x *Oidb_0X769_UinPackageUsedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_service_pb_oidb_0x769_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oidb_0X769_UinPackageUsedInfo.ProtoReflect.Descriptor instead.
func (*Oidb_0X769_UinPackageUsedInfo) Descriptor() ([]byte, []int) {
	return file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP(), []int{0, 14}
}

func (x *Oidb_0X769_UinPackageUsedInfo) GetRuleId() uint32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *Oidb_0X769_UinPackageUsedInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Oidb_0X769_UinPackageUsedInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Oidb_0X769_UinPackageUsedInfo) GetUinNum() uint64 {
	if x != nil {
		return x.UinNum
	}
	return 0
}

var File_daemon_service_pb_oidb_0x769_proto protoreflect.FileDescriptor

var file_daemon_service_pb_oidb_0x769_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78, 0x37, 0x36, 0x39, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x10, 0x0a, 0x0a, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78,
	0x37, 0x36, 0x39, 0x1a, 0x4f, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x1a, 0x56, 0x0a, 0x06, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x1a, 0xb5, 0x01, 0x0a,
	0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x75,
	0x67, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x62,
	0x75, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x3d, 0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78, 0x37, 0x36, 0x39, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x0e, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x1a, 0x39, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a,
	0x58, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0xe2, 0x01, 0x0a, 0x0a, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x21, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78, 0x37, 0x36, 0x39, 0x2e, 0x43,
	0x50, 0x55, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x2a, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30,
	0x78, 0x37, 0x36, 0x39, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78, 0x37, 0x36,
	0x39, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78, 0x37, 0x36, 0x39, 0x2e,
	0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x06, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x1a, 0x38,
	0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x74, 0x0a, 0x08, 0x43, 0x37, 0x32, 0x34,
	0x37, 0x38, 0x4f, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x64, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x6f, 0x6d, 0x1a, 0x51,
	0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x0d, 0x75, 0x69, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x1a, 0xe6, 0x01, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x69, 0x6e, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x75, 0x69,
	0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x65, 0x66,
	0x74, 0x55, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x75,
	0x69, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x61,
	0x78, 0x55, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x72, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x70, 0x6f, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x15, 0x75, 0x69, 0x6e, 0x5f, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78,
	0x37, 0x36, 0x39, 0x2e, 0x55, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x55, 0x73,
	0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x12, 0x75, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x55, 0x73, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0xcc, 0x02, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x36, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4f, 0x69,
	0x64, 0x62, 0x5f, 0x30, 0x78, 0x37, 0x36, 0x39, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53,
	0x65, 0x71, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3e,
	0x0a, 0x0f, 0x6d, 0x73, 0x67, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30,
	0x78, 0x37, 0x36, 0x39, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0d, 0x6d, 0x73, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x61, 0x0a, 0x1b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f,
	0x75, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x4f, 0x69,
	0x64, 0x62, 0x5f, 0x30, 0x78, 0x37, 0x36, 0x39, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x69,
	0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x52, 0x17, 0x71, 0x75, 0x65, 0x72, 0x79, 0x55, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0xb9, 0x01, 0x0a, 0x07, 0x52, 0x73,
	0x70, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x33, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30, 0x78, 0x37, 0x36, 0x39, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x61, 0x0a, 0x1b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x75, 0x69, 0x6e, 0x5f,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x73,
	0x70, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x4f, 0x69, 0x64, 0x62, 0x5f, 0x30,
	0x78, 0x37, 0x36, 0x39, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x69, 0x6e, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x52, 0x17, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x55, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x73, 0x70, 0x1a, 0x7f, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x70, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x64, 0x70, 0x69, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x74,
	0x6f, 0x75, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x1a, 0x3f, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x1a, 0x70, 0x0a, 0x12, 0x55, 0x69, 0x6e, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x55, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x72, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x69, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x70, 0x35, 0x65, 0x2f, 0x70,
	0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_service_pb_oidb_0x769_proto_rawDescOnce sync.Once
	file_daemon_service_pb_oidb_0x769_proto_rawDescData = file_daemon_service_pb_oidb_0x769_proto_rawDesc
)

func file_daemon_service_pb_oidb_0x769_proto_rawDescGZIP() []byte {
	file_daemon_service_pb_oidb_0x769_proto_rawDescOnce.Do(func() {
		file_daemon_service_pb_oidb_0x769_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_service_pb_oidb_0x769_proto_rawDescData)
	})
	return file_daemon_service_pb_oidb_0x769_proto_rawDescData
}

var file_daemon_service_pb_oidb_0x769_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_daemon_service_pb_oidb_0x769_proto_goTypes = []interface{}{
	(*Oidb_0X769)(nil),                         // 0: Oidb_0x769
	(*Oidb_0X769_CPU)(nil),                     // 1: Oidb_0x769.CPU
	(*Oidb_0X769_Camera)(nil),                  // 2: Oidb_0x769.Camera
	(*Oidb_0X769_Config)(nil),                  // 3: Oidb_0x769.Config
	(*Oidb_0X769_ConfigSeq)(nil),               // 4: Oidb_0x769.ConfigSeq
	(*Oidb_0X769_Content)(nil),                 // 5: Oidb_0x769.Content
	(*Oidb_0X769_DeviceInfo)(nil),              // 6: Oidb_0x769.DeviceInfo
	(*Oidb_0X769_Memory)(nil),                  // 7: Oidb_0x769.Memory
	(*Oidb_0X769_C72478OS)(nil),                // 8: Oidb_0x769.C72478OS
	(*Oidb_0X769_QueryUinPackageUsageReq)(nil), // 9: Oidb_0x769.QueryUinPackageUsageReq
	(*Oidb_0X769_QueryUinPackageUsageRsp)(nil), // 10: Oidb_0x769.QueryUinPackageUsageRsp
	(*Oidb_0X769_ReqBody)(nil),                 // 11: Oidb_0x769.ReqBody
	(*Oidb_0X769_RspBody)(nil),                 // 12: Oidb_0x769.RspBody
	(*Oidb_0X769_Screen)(nil),                  // 13: Oidb_0x769.Screen
	(*Oidb_0X769_Storage)(nil),                 // 14: Oidb_0x769.Storage
	(*Oidb_0X769_UinPackageUsedInfo)(nil),      // 15: Oidb_0x769.UinPackageUsedInfo
}
var file_daemon_service_pb_oidb_0x769_proto_depIdxs = []int32{
	5,  // 0: Oidb_0x769.Config.msg_content_list:type_name -> Oidb_0x769.Content
	1,  // 1: Oidb_0x769.DeviceInfo.cpu:type_name -> Oidb_0x769.CPU
	7,  // 2: Oidb_0x769.DeviceInfo.memory:type_name -> Oidb_0x769.Memory
	14, // 3: Oidb_0x769.DeviceInfo.storage:type_name -> Oidb_0x769.Storage
	13, // 4: Oidb_0x769.DeviceInfo.screen:type_name -> Oidb_0x769.Screen
	15, // 5: Oidb_0x769.QueryUinPackageUsageRsp.uin_package_used_list:type_name -> Oidb_0x769.UinPackageUsedInfo
	4,  // 6: Oidb_0x769.ReqBody.config_list:type_name -> Oidb_0x769.ConfigSeq
	6,  // 7: Oidb_0x769.ReqBody.msg_device_info:type_name -> Oidb_0x769.DeviceInfo
	9,  // 8: Oidb_0x769.ReqBody.query_uin_package_usage_req:type_name -> Oidb_0x769.QueryUinPackageUsageReq
	3,  // 9: Oidb_0x769.RspBody.config_list:type_name -> Oidb_0x769.Config
	10, // 10: Oidb_0x769.RspBody.query_uin_package_usage_rsp:type_name -> Oidb_0x769.QueryUinPackageUsageRsp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_daemon_service_pb_oidb_0x769_proto_init() }
func file_daemon_service_pb_oidb_0x769_proto_init() {
	if File_daemon_service_pb_oidb_0x769_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_CPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_Camera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_ConfigSeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_DeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_Memory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_C72478OS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_QueryUinPackageUsageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_QueryUinPackageUsageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_ReqBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_RspBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_Screen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_service_pb_oidb_0x769_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oidb_0X769_UinPackageUsedInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_service_pb_oidb_0x769_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daemon_service_pb_oidb_0x769_proto_goTypes,
		DependencyIndexes: file_daemon_service_pb_oidb_0x769_proto_depIdxs,
		MessageInfos:      file_daemon_service_pb_oidb_0x769_proto_msgTypes,
	}.Build()
	File_daemon_service_pb_oidb_0x769_proto = out.File
	file_daemon_service_pb_oidb_0x769_proto_rawDesc = nil
	file_daemon_service_pb_oidb_0x769_proto_goTypes = nil
	file_daemon_service_pb_oidb_0x769_proto_depIdxs = nil
}
