// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pkg/encoding/trpc/pb/oidb_sso.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message generated by proto-message-gen. DO NOT EDIT.
// source: tencent.p1399im.oidb.oidb_sso
//
// oidb_sso is the message type for the oidb_sso.
type OidbSso struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OidbSso) Reset() {
	*x = OidbSso{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OidbSso) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OidbSso) ProtoMessage() {}

func (x *OidbSso) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OidbSso.ProtoReflect.Descriptor instead.
func (*OidbSso) Descriptor() ([]byte, []int) {
	return file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescGZIP(), []int{0}
}

// MetaData is the message type for the MetaData.
type OidbSso_MetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // key
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // value
}

func (x *OidbSso_MetaData) Reset() {
	*x = OidbSso_MetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OidbSso_MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OidbSso_MetaData) ProtoMessage() {}

func (x *OidbSso_MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OidbSso_MetaData.ProtoReflect.Descriptor instead.
func (*OidbSso_MetaData) Descriptor() ([]byte, []int) {
	return file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OidbSso_MetaData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OidbSso_MetaData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// OIDBSSOPkg is the message type for the OIDBSSOPkg.
type OidbSso_OIDBSSOPkg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bodybuffer    []byte              `protobuf:"bytes,4,opt,name=bodybuffer,proto3" json:"bodybuffer,omitempty"`                               // bytes_bodybuffer
	ClientVersion string              `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`    // str_client_version
	ErrorMsg      string              `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`                   // str_error_msg
	TrpcTransInfo []*OidbSso_MetaData `protobuf:"bytes,11,rep,name=trpc_trans_info,json=trpcTransInfo,proto3" json:"trpc_trans_info,omitempty"` // trpc_trans_info
	Command       uint32              `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`                                    // uint32_command
	Result        uint32              `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`                                      // uint32_result
	ServiceType   uint32              `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`         // uint32_service_type
}

func (x *OidbSso_OIDBSSOPkg) Reset() {
	*x = OidbSso_OIDBSSOPkg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OidbSso_OIDBSSOPkg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OidbSso_OIDBSSOPkg) ProtoMessage() {}

func (x *OidbSso_OIDBSSOPkg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OidbSso_OIDBSSOPkg.ProtoReflect.Descriptor instead.
func (*OidbSso_OIDBSSOPkg) Descriptor() ([]byte, []int) {
	return file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescGZIP(), []int{0, 1}
}

func (x *OidbSso_OIDBSSOPkg) GetBodybuffer() []byte {
	if x != nil {
		return x.Bodybuffer
	}
	return nil
}

func (x *OidbSso_OIDBSSOPkg) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *OidbSso_OIDBSSOPkg) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *OidbSso_OIDBSSOPkg) GetTrpcTransInfo() []*OidbSso_MetaData {
	if x != nil {
		return x.TrpcTransInfo
	}
	return nil
}

func (x *OidbSso_OIDBSSOPkg) GetCommand() uint32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *OidbSso_OIDBSSOPkg) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *OidbSso_OIDBSSOPkg) GetServiceType() uint32 {
	if x != nil {
		return x.ServiceType
	}
	return 0
}

var File_pkg_encoding_trpc_pb_oidb_sso_proto protoreflect.FileDescriptor

var file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x74,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x69, 0x64, 0x62, 0x5f, 0x73, 0x73, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x02, 0x0a, 0x08, 0x6f, 0x69, 0x64, 0x62, 0x5f, 0x73,
	0x73, 0x6f, 0x1a, 0x32, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x81, 0x02, 0x0a, 0x0a, 0x4f, 0x49, 0x44, 0x42, 0x53,
	0x53, 0x4f, 0x50, 0x6b, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x62,
	0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x3a, 0x0a, 0x0f, 0x74, 0x72, 0x70,
	0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x69, 0x64, 0x62, 0x5f, 0x73, 0x73, 0x6f, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x74, 0x72, 0x70, 0x63, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x70, 0x35, 0x65, 0x2f,
	0x70, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescOnce sync.Once
	file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescData = file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDesc
)

func file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescGZIP() []byte {
	file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescOnce.Do(func() {
		file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescData)
	})
	return file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDescData
}

var file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_encoding_trpc_pb_oidb_sso_proto_goTypes = []interface{}{
	(*OidbSso)(nil),            // 0: oidb_sso
	(*OidbSso_MetaData)(nil),   // 1: oidb_sso.MetaData
	(*OidbSso_OIDBSSOPkg)(nil), // 2: oidb_sso.OIDBSSOPkg
}
var file_pkg_encoding_trpc_pb_oidb_sso_proto_depIdxs = []int32{
	1, // 0: oidb_sso.OIDBSSOPkg.trpc_trans_info:type_name -> oidb_sso.MetaData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_encoding_trpc_pb_oidb_sso_proto_init() }
func file_pkg_encoding_trpc_pb_oidb_sso_proto_init() {
	if File_pkg_encoding_trpc_pb_oidb_sso_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OidbSso); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OidbSso_MetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OidbSso_OIDBSSOPkg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_encoding_trpc_pb_oidb_sso_proto_goTypes,
		DependencyIndexes: file_pkg_encoding_trpc_pb_oidb_sso_proto_depIdxs,
		MessageInfos:      file_pkg_encoding_trpc_pb_oidb_sso_proto_msgTypes,
	}.Build()
	File_pkg_encoding_trpc_pb_oidb_sso_proto = out.File
	file_pkg_encoding_trpc_pb_oidb_sso_proto_rawDesc = nil
	file_pkg_encoding_trpc_pb_oidb_sso_proto_goTypes = nil
	file_pkg_encoding_trpc_pb_oidb_sso_proto_depIdxs = nil
}
