// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: daemon/message/pb/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Copyright 2022 Elapse and contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// IMMsgBodyElem is the message type for the IMMsgBodyElem.
type IMMsgBodyElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMMsgBodyElem) Reset() {
	*x = IMMsgBodyElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_message_pb_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsgBodyElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsgBodyElem) ProtoMessage() {}

func (x *IMMsgBodyElem) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_message_pb_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsgBodyElem.ProtoReflect.Descriptor instead.
func (*IMMsgBodyElem) Descriptor() ([]byte, []int) {
	return file_daemon_message_pb_message_proto_rawDescGZIP(), []int{0}
}

type IMMsgBodyElem_TextPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field3 int32                        `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
	Field4 int32                        `protobuf:"varint,4,opt,name=field4,proto3" json:"field4,omitempty"`
	TinyId int64                        `protobuf:"varint,5,opt,name=tiny_id,json=tinyId,proto3" json:"tiny_id,omitempty"`
	Roles  []*IMMsgBodyElem_TextPb_Role `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *IMMsgBodyElem_TextPb) Reset() {
	*x = IMMsgBodyElem_TextPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_message_pb_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsgBodyElem_TextPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsgBodyElem_TextPb) ProtoMessage() {}

func (x *IMMsgBodyElem_TextPb) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_message_pb_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsgBodyElem_TextPb.ProtoReflect.Descriptor instead.
func (*IMMsgBodyElem_TextPb) Descriptor() ([]byte, []int) {
	return file_daemon_message_pb_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IMMsgBodyElem_TextPb) GetField3() int32 {
	if x != nil {
		return x.Field3
	}
	return 0
}

func (x *IMMsgBodyElem_TextPb) GetField4() int32 {
	if x != nil {
		return x.Field4
	}
	return 0
}

func (x *IMMsgBodyElem_TextPb) GetTinyId() int64 {
	if x != nil {
		return x.TinyId
	}
	return 0
}

func (x *IMMsgBodyElem_TextPb) GetRoles() []*IMMsgBodyElem_TextPb_Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type IMMsgBodyElem_TextPb_Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64                           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Info  *IMMsgBodyElem_TextPb_Role_Info `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Hoist bool                            `protobuf:"varint,3,opt,name=hoist,proto3" json:"hoist,omitempty"`
}

func (x *IMMsgBodyElem_TextPb_Role) Reset() {
	*x = IMMsgBodyElem_TextPb_Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_message_pb_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsgBodyElem_TextPb_Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsgBodyElem_TextPb_Role) ProtoMessage() {}

func (x *IMMsgBodyElem_TextPb_Role) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_message_pb_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsgBodyElem_TextPb_Role.ProtoReflect.Descriptor instead.
func (*IMMsgBodyElem_TextPb_Role) Descriptor() ([]byte, []int) {
	return file_daemon_message_pb_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *IMMsgBodyElem_TextPb_Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IMMsgBodyElem_TextPb_Role) GetInfo() *IMMsgBodyElem_TextPb_Role_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *IMMsgBodyElem_TextPb_Role) GetHoist() bool {
	if x != nil {
		return x.Hoist
	}
	return false
}

type IMMsgBodyElem_TextPb_Role_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Color int32  `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Hoist bool   `protobuf:"varint,4,opt,name=hoist,proto3" json:"hoist,omitempty"`
}

func (x *IMMsgBodyElem_TextPb_Role_Info) Reset() {
	*x = IMMsgBodyElem_TextPb_Role_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_message_pb_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMMsgBodyElem_TextPb_Role_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMsgBodyElem_TextPb_Role_Info) ProtoMessage() {}

func (x *IMMsgBodyElem_TextPb_Role_Info) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_message_pb_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMsgBodyElem_TextPb_Role_Info.ProtoReflect.Descriptor instead.
func (*IMMsgBodyElem_TextPb_Role_Info) Descriptor() ([]byte, []int) {
	return file_daemon_message_pb_message_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *IMMsgBodyElem_TextPb_Role_Info) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IMMsgBodyElem_TextPb_Role_Info) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IMMsgBodyElem_TextPb_Role_Info) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *IMMsgBodyElem_TextPb_Role_Info) GetHoist() bool {
	if x != nil {
		return x.Hoist
	}
	return false
}

var File_daemon_message_pb_message_proto protoreflect.FileDescriptor

var file_daemon_message_pb_message_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd3, 0x02, 0x0a, 0x0d, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x45,
	0x6c, 0x65, 0x6d, 0x1a, 0xc1, 0x02, 0x0a, 0x06, 0x54, 0x65, 0x78, 0x74, 0x50, 0x62, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x34,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x34, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x69, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x74, 0x69, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x42, 0x6f,
	0x64, 0x79, 0x45, 0x6c, 0x65, 0x6d, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x50, 0x62, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x1a, 0xbb, 0x01, 0x0a, 0x04, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x33, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x49, 0x4d, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x45, 0x6c, 0x65, 0x6d,
	0x2e, 0x54, 0x65, 0x78, 0x74, 0x50, 0x62, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x2e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x68, 0x6f, 0x69, 0x73, 0x74, 0x1a, 0x58, 0x0a,
	0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x68, 0x6f, 0x69, 0x73, 0x74, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x70, 0x35, 0x65, 0x2f, 0x70, 0x65, 0x6e,
	0x67, 0x75, 0x69, 0x6e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_message_pb_message_proto_rawDescOnce sync.Once
	file_daemon_message_pb_message_proto_rawDescData = file_daemon_message_pb_message_proto_rawDesc
)

func file_daemon_message_pb_message_proto_rawDescGZIP() []byte {
	file_daemon_message_pb_message_proto_rawDescOnce.Do(func() {
		file_daemon_message_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_message_pb_message_proto_rawDescData)
	})
	return file_daemon_message_pb_message_proto_rawDescData
}

var file_daemon_message_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_daemon_message_pb_message_proto_goTypes = []interface{}{
	(*IMMsgBodyElem)(nil),                  // 0: IMMsgBodyElem
	(*IMMsgBodyElem_TextPb)(nil),           // 1: IMMsgBodyElem.TextPb
	(*IMMsgBodyElem_TextPb_Role)(nil),      // 2: IMMsgBodyElem.TextPb.Role
	(*IMMsgBodyElem_TextPb_Role_Info)(nil), // 3: IMMsgBodyElem.TextPb.Role.Info
}
var file_daemon_message_pb_message_proto_depIdxs = []int32{
	2, // 0: IMMsgBodyElem.TextPb.roles:type_name -> IMMsgBodyElem.TextPb.Role
	3, // 1: IMMsgBodyElem.TextPb.Role.info:type_name -> IMMsgBodyElem.TextPb.Role.Info
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_daemon_message_pb_message_proto_init() }
func file_daemon_message_pb_message_proto_init() {
	if File_daemon_message_pb_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daemon_message_pb_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsgBodyElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_message_pb_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsgBodyElem_TextPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_message_pb_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsgBodyElem_TextPb_Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_message_pb_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMMsgBodyElem_TextPb_Role_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_message_pb_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daemon_message_pb_message_proto_goTypes,
		DependencyIndexes: file_daemon_message_pb_message_proto_depIdxs,
		MessageInfos:      file_daemon_message_pb_message_proto_msgTypes,
	}.Build()
	File_daemon_message_pb_message_proto = out.File
	file_daemon_message_pb_message_proto_rawDesc = nil
	file_daemon_message_pb_message_proto_goTypes = nil
	file_daemon_message_pb_message_proto_depIdxs = nil
}
