// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: daemon/message/pb/sub_type_0xc1.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message generated by proto-message-gen. DO NOT EDIT.
// source: tencent.p1298im.c2c.msgtype0xa6.submsgtype0xc1.SubMsgType0xc1
//
// SubMsgType0xc1 is the message type for the SubMsgType0xc1.
type SubMsgType0Xc1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubMsgType0Xc1) Reset() {
	*x = SubMsgType0Xc1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMsgType0Xc1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMsgType0Xc1) ProtoMessage() {}

func (x *SubMsgType0Xc1) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMsgType0Xc1.ProtoReflect.Descriptor instead.
func (*SubMsgType0Xc1) Descriptor() ([]byte, []int) {
	return file_daemon_message_pb_sub_type_0xc1_proto_rawDescGZIP(), []int{0}
}

// MsgBody is the message type for the MsgBody.
type SubMsgType0Xc1_MsgBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileKey              []byte                         `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`                                           // bytes_file_key
	FromUin              uint64                         `protobuf:"varint,2,opt,name=from_uin,json=fromUin,proto3" json:"from_uin,omitempty"`                                          // uint64_from_uin
	ToUin                uint64                         `protobuf:"varint,3,opt,name=to_uin,json=toUin,proto3" json:"to_uin,omitempty"`                                                // uint64_to_uin
	Status               uint32                         `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                                                           // uint32_status
	Ttl                  uint32                         `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`                                                                 // uint32_ttl
	Type                 uint32                         `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`                                                               // uint32_type
	EncryptPreheadLength uint32                         `protobuf:"varint,7,opt,name=encrypt_prehead_length,json=encryptPreheadLength,proto3" json:"encrypt_prehead_length,omitempty"` // uint32_encrypt_prehead_length
	EncryptType          uint32                         `protobuf:"varint,8,opt,name=encrypt_type,json=encryptType,proto3" json:"encrypt_type,omitempty"`                              // uint32_encrypt_type
	EncryptKey           []byte                         `protobuf:"bytes,9,opt,name=encrypt_key,json=encryptKey,proto3" json:"encrypt_key,omitempty"`                                  // bytes_encrypt_key
	ReadTimes            uint32                         `protobuf:"varint,10,opt,name=read_times,json=readTimes,proto3" json:"read_times,omitempty"`                                   // uint32_read_times
	LeftTime             uint32                         `protobuf:"varint,11,opt,name=left_time,json=leftTime,proto3" json:"left_time,omitempty"`                                      // uint32_left_time
	NotOnlineImage       *SubMsgType0Xc1_NotOnlineImage `protobuf:"bytes,12,opt,name=not_online_image,json=notOnlineImage,proto3" json:"not_online_image,omitempty"`                   // not_online_image
}

func (x *SubMsgType0Xc1_MsgBody) Reset() {
	*x = SubMsgType0Xc1_MsgBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMsgType0Xc1_MsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMsgType0Xc1_MsgBody) ProtoMessage() {}

func (x *SubMsgType0Xc1_MsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMsgType0Xc1_MsgBody.ProtoReflect.Descriptor instead.
func (*SubMsgType0Xc1_MsgBody) Descriptor() ([]byte, []int) {
	return file_daemon_message_pb_sub_type_0xc1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SubMsgType0Xc1_MsgBody) GetFileKey() []byte {
	if x != nil {
		return x.FileKey
	}
	return nil
}

func (x *SubMsgType0Xc1_MsgBody) GetFromUin() uint64 {
	if x != nil {
		return x.FromUin
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetToUin() uint64 {
	if x != nil {
		return x.ToUin
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetEncryptPreheadLength() uint32 {
	if x != nil {
		return x.EncryptPreheadLength
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetEncryptType() uint32 {
	if x != nil {
		return x.EncryptType
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetEncryptKey() []byte {
	if x != nil {
		return x.EncryptKey
	}
	return nil
}

func (x *SubMsgType0Xc1_MsgBody) GetReadTimes() uint32 {
	if x != nil {
		return x.ReadTimes
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetLeftTime() uint32 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

func (x *SubMsgType0Xc1_MsgBody) GetNotOnlineImage() *SubMsgType0Xc1_NotOnlineImage {
	if x != nil {
		return x.NotOnlineImage
	}
	return nil
}

// NotOnlineImage is the message type for the NotOnlineImage.
type SubMsgType0Xc1_NotOnlineImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath       []byte `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                       // file_path
	FileLen        uint32 `protobuf:"varint,2,opt,name=file_len,json=fileLen,proto3" json:"file_len,omitempty"`                         // file_len
	DownloadPath   []byte `protobuf:"bytes,3,opt,name=download_path,json=downloadPath,proto3" json:"download_path,omitempty"`           // download_path
	OldVerSendFile []byte `protobuf:"bytes,4,opt,name=old_ver_send_file,json=oldVerSendFile,proto3" json:"old_ver_send_file,omitempty"` // old_ver_send_file
	ImgType        uint32 `protobuf:"varint,5,opt,name=img_type,json=imgType,proto3" json:"img_type,omitempty"`                         // img_type
	PreviewsImage  []byte `protobuf:"bytes,6,opt,name=previews_image,json=previewsImage,proto3" json:"previews_image,omitempty"`        // previews_image
	PicMd5         []byte `protobuf:"bytes,7,opt,name=pic_md5,json=picMd5,proto3" json:"pic_md5,omitempty"`                             // pic_md5
	PicHeight      uint32 `protobuf:"varint,8,opt,name=pic_height,json=picHeight,proto3" json:"pic_height,omitempty"`                   // pic_height
	PicWidth       uint32 `protobuf:"varint,9,opt,name=pic_width,json=picWidth,proto3" json:"pic_width,omitempty"`                      // pic_width
	ResId          []byte `protobuf:"bytes,10,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`                               // res_id
	Flag           []byte `protobuf:"bytes,11,opt,name=flag,proto3" json:"flag,omitempty"`                                              // flag
	DownloadUrl    string `protobuf:"bytes,12,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`             // str_download_url
	Original       uint32 `protobuf:"varint,13,opt,name=original,proto3" json:"original,omitempty"`                                     // original
}

func (x *SubMsgType0Xc1_NotOnlineImage) Reset() {
	*x = SubMsgType0Xc1_NotOnlineImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMsgType0Xc1_NotOnlineImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMsgType0Xc1_NotOnlineImage) ProtoMessage() {}

func (x *SubMsgType0Xc1_NotOnlineImage) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMsgType0Xc1_NotOnlineImage.ProtoReflect.Descriptor instead.
func (*SubMsgType0Xc1_NotOnlineImage) Descriptor() ([]byte, []int) {
	return file_daemon_message_pb_sub_type_0xc1_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetFilePath() []byte {
	if x != nil {
		return x.FilePath
	}
	return nil
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetFileLen() uint32 {
	if x != nil {
		return x.FileLen
	}
	return 0
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetDownloadPath() []byte {
	if x != nil {
		return x.DownloadPath
	}
	return nil
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetOldVerSendFile() []byte {
	if x != nil {
		return x.OldVerSendFile
	}
	return nil
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetImgType() uint32 {
	if x != nil {
		return x.ImgType
	}
	return 0
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetPreviewsImage() []byte {
	if x != nil {
		return x.PreviewsImage
	}
	return nil
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetPicMd5() []byte {
	if x != nil {
		return x.PicMd5
	}
	return nil
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetPicHeight() uint32 {
	if x != nil {
		return x.PicHeight
	}
	return 0
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetPicWidth() uint32 {
	if x != nil {
		return x.PicWidth
	}
	return 0
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetResId() []byte {
	if x != nil {
		return x.ResId
	}
	return nil
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetFlag() []byte {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *SubMsgType0Xc1_NotOnlineImage) GetOriginal() uint32 {
	if x != nil {
		return x.Original
	}
	return 0
}

var File_daemon_message_pb_sub_type_0xc1_proto protoreflect.FileDescriptor

var file_daemon_message_pb_sub_type_0xc1_proto_rawDesc = []byte{
	0x0a, 0x25, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2f, 0x70, 0x62, 0x2f, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x30, 0x78, 0x63,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x06, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x30, 0x78, 0x63, 0x31, 0x1a, 0x94, 0x03, 0x0a, 0x07, 0x4d,
	0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x6e, 0x12, 0x15, 0x0a, 0x06,
	0x74, 0x6f, 0x5f, 0x75, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f,
	0x55, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x74, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x34, 0x0a, 0x16, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x70, 0x72, 0x65,
	0x68, 0x65, 0x61, 0x64, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x14, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x50, 0x72, 0x65, 0x68, 0x65, 0x61,
	0x64, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x72, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65,
	0x66, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c,
	0x65, 0x66, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x10, 0x6e, 0x6f, 0x74, 0x5f, 0x6f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x53, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x30, 0x78,
	0x63, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x1a, 0x99, 0x03, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x29, 0x0a, 0x11, 0x6f, 0x6c, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x6e,
	0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x6f, 0x6c,
	0x64, 0x56, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x6d, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x69, 0x6d, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x69, 0x63, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x70, 0x69, 0x63, 0x4d, 0x64, 0x35, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x69, 0x63, 0x5f, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x69, 0x63,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x69, 0x63, 0x5f, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x69, 0x63, 0x57, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x65, 0x73, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x61, 0x70,
	0x35, 0x65, 0x2f, 0x70, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_message_pb_sub_type_0xc1_proto_rawDescOnce sync.Once
	file_daemon_message_pb_sub_type_0xc1_proto_rawDescData = file_daemon_message_pb_sub_type_0xc1_proto_rawDesc
)

func file_daemon_message_pb_sub_type_0xc1_proto_rawDescGZIP() []byte {
	file_daemon_message_pb_sub_type_0xc1_proto_rawDescOnce.Do(func() {
		file_daemon_message_pb_sub_type_0xc1_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_message_pb_sub_type_0xc1_proto_rawDescData)
	})
	return file_daemon_message_pb_sub_type_0xc1_proto_rawDescData
}

var file_daemon_message_pb_sub_type_0xc1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_daemon_message_pb_sub_type_0xc1_proto_goTypes = []interface{}{
	(*SubMsgType0Xc1)(nil),                // 0: SubMsgType0xc1
	(*SubMsgType0Xc1_MsgBody)(nil),        // 1: SubMsgType0xc1.MsgBody
	(*SubMsgType0Xc1_NotOnlineImage)(nil), // 2: SubMsgType0xc1.NotOnlineImage
}
var file_daemon_message_pb_sub_type_0xc1_proto_depIdxs = []int32{
	2, // 0: SubMsgType0xc1.MsgBody.not_online_image:type_name -> SubMsgType0xc1.NotOnlineImage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_daemon_message_pb_sub_type_0xc1_proto_init() }
func file_daemon_message_pb_sub_type_0xc1_proto_init() {
	if File_daemon_message_pb_sub_type_0xc1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMsgType0Xc1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMsgType0Xc1_MsgBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_message_pb_sub_type_0xc1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMsgType0Xc1_NotOnlineImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_message_pb_sub_type_0xc1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daemon_message_pb_sub_type_0xc1_proto_goTypes,
		DependencyIndexes: file_daemon_message_pb_sub_type_0xc1_proto_depIdxs,
		MessageInfos:      file_daemon_message_pb_sub_type_0xc1_proto_msgTypes,
	}.Build()
	File_daemon_message_pb_sub_type_0xc1_proto = out.File
	file_daemon_message_pb_sub_type_0xc1_proto_rawDesc = nil
	file_daemon_message_pb_sub_type_0xc1_proto_goTypes = nil
	file_daemon_message_pb_sub_type_0xc1_proto_depIdxs = nil
}
