name: Build branch/main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - name: Build Binaries
        run: bash scripts/release.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/releases
